### ISSUE TITLE
Example images

### ISSUE THREAD

**Issue by neozhaoliang** [neozhaoliang/Hyperbolic-Honeycombs#1]

**Comment by neozhaoliang** [comment]
...

**Comment by antirez** [comment]
Hello, thanks for your work. I wonder what is the license under the above images are released. Thank you.

**Comment by neozhaoliang** [comment]
It's the MIT license. I'll add this to readme file later.

**Comment by neozhaoliang** [comment]
![66](https://user-images.githubusercontent.com/23307174/134807646-1fa40b62-927e-479c-b9dd-dddcc9c6ad26.png)
![33](https://user-images.githubusercontent.com/23307174/134812638-1fa41d7f-cf64-4d7d-bab6-a0345e1cc74e.png)

**Comment by neozhaoliang** [comment]
![88](https://user-images.githubusercontent.com/23307174/134965720-617ca96c-8f5f-4977-a9c8-1f8282e0cea3.png)
![77](https://user-images.githubusercontent.com/23307174/134814347-eee983bf-9b46-4121-96a5-9dd1274baa0a.png)

**Comment by neozhaoliang** [comment]
![图片](https://user-images.githubusercontent.com/23307174/217011897-71ed5747-7659-4208-a1f2-fd135bae47ad.png)

**Comment by antirez** [comment]
Thank you

Salvatore Sanfilippo

"My task is not difficult; all I would need is to be immortal to accomplish
it." -- Jorge Luis Borges.
